# DevBuddy config file
# See https://github.com/devbuddy/devbuddy/blob/master/docs/Config.md

up:
  - go:
      version: 1.16.3
      modules: true
  - custom:
      name: Install golangci-lint
      met?: which golangci-lint
      meet: go get -u github.com/golangci/golangci-lint/cmd/golangci-lint

commands:
  test:
    run: go test -cover -race ./...
  lint:
    run: golangci-lint run
  tidy:
    run: go mod tidy

open:
  devbuddy: https://github.com/devbuddy/devbuddy/blob/main/docs/Config.md#config-devyml
